### ISSUE TITLE
Missing textures on HUD's player model

### ISSUE THREAD

**Issue by Rehrn** [yesod404/yesodCollyHUD#10]
I have no idea if it's caused because my config is low as hell or there's something missing in the files but there is no background on the little player model just classic missingtexture, btw I installed the HUD via tf2huds.com (If it helps).

![image](https://github.com/yesod404/yesodCollyHUD/assets/81170640/a6d7f684-d9b1-49ab-aa9b-aa1a92d17df5)

**Comment by Rehrn** [comment]
Apparently it just happen in casual, I tried community servers and the error is fixed, lol.

**Comment by yesod404** [comment]
I am trying to figure out what is causing that, too. I will let you know as soon as possible if I can/cannot fix it.

**Comment by yesod404** [comment]
I just fixed the issue, the file was located in hud/ so it was restricted, but I moved it to thumbnails, so now everything should be good.
