### ISSUE TITLE
Spy Disguise on bottom left not aligned with screenshot in the folder

### ISSUE THREAD

**Issue by Kurumesu** [yesod404/yesodCollyHUD#15]
![image](https://github.com/user-attachments/assets/3791a21b-ea14-4e41-9ae4-3c61123fff43)

Seems to be a bit off, even though I put what was needed in scripts/hudlayout.res

**Comment by yesod404** [comment]
This style of disguise is meant to be centered. If you want the centered style to be bottom left better, you must manually change the positioning.

So I am not just assuming, are you trying to have that style in the bottom left, or are you confused on how to change the position in hudlayout?

**Comment by Kurumesu** [comment]
Trying to have it in bottom left

**Comment by yesod404** [comment]
The screenshots are meant to show what the style is supposed to be for the bottom left or centered. You are using the centered style with the bottom left positioning. If you want the bottom left version, copy and paste the disguisestatuspanel in the bottom left folder and put it in resource/ui/

![Spy Disguise](https://github.com/user-attachments/assets/49455c20-6fc0-400b-9c4c-e2c3fe78186d)
