### ISSUE TITLE
MvM class selection menu not appearing

### ISSUE THREAD

**Issue by ThatCatt-0-o** [yesod404/yesodCollyHUD#17]
Hey its me again, I wanted to signal another bug that ive seen in MvM, so basically i cant choose any class and even if i press my class selection button nothing will appear im just stuck in the camera for the class selection menu. But if i launch another game it fixes it ?? i even tried using hud_reloadscheme in the console and it didnt do anything.

**Comment by yesod404** [comment]
I never encountered this problem, and I cannot replicate the bug, so it might be your end?
