### ISSUE TITLE
mvm win menu

### ISSUE THREAD

**Issue by r3dnasa** [yesod404/yesodCollyHUD#6]
![20240614040400_1](https://github.com/yesod404/yesodCollyHUD/assets/82971054/2e36d253-746f-4d3c-81bd-f8d72e9f5c8f)
i think screenshot is pretty evident

**Comment by yesod404** [comment]
Lol yeah, I honestly chose to skip out on this so I could release the HUD, because it is such a nightmare to get the MvM panels to work. I am not sure how to make a base so I could simply copy paste, and I did not want to play an entire thing of MvM to see if my one change fixed everything.

**Comment by r3dnasa** [comment]
looks great
